PDF_VIEWER_LVGL_LICENSE = Public Domain

PDF_VIEWER_LVGL_VERSION = 0.0.1
PDF_VIEWER_LVGL_SITE = https://github.com/tyano463/pdf_viewer_lvgl
#PDF_VIEWER_LVGL_SITE = /home/tyano/workspace/pdf/pdf_viewer_lvgl
PDF_VIEWER_LVGL_SITE_VERSION = $(PDF_VIEWER_LVGL_VERSION)
PDF_VIEWER_LVGL_SITE_METHOD = git
#PDF_VIEWER_LVGL_SITE_METHOD = local
PDF_VIEWER_LVGL_GIT_SUBMODULES = YES
PDF_VIEWER_LVGL_AUTORECONF = YES
PDF_VIEWER_LVGL_AUTORECONF_OPTS = --force

PDF_VIEWER_LVGL_DEPENDENCIES = mupdf

$(eval $(autotools-package))

